-- 코드를 입력하세요
SELECT PRODUCT_CODE, SUM(A.PRICE * B.SALES_AMOUNT) AS SALES
  FROM PRODUCT A
  JOIN OFFLINE_SALE B ON B.PRODUCT_ID = A.PRODUCT_ID
 GROUP BY PRODUCT_CODE
 ORDER BY SALES DESC, PRODUCT_CODE