-- 코드를 작성해주세요
SELECT SUM(A.cnt) AS FISH_COUNT
  FROM(SELECT COUNT(*) AS cnt, FISH_TYPE
         FROM FISH_INFO 
        GROUP BY FISH_TYPE) A
  JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
 WHERE B.FISH_NAME IN ('BASS', 'SNAPPER')